# _config.yml

title: Steffen Energy LLC
description: "Strategic guidance for a transforming energy landscape. Expert project management, technical writing, and policy advisory for the future of energy."
url: "https://www.steffenenergy.com"